### PR TITLE
Updated the landfire_veg_param.csv with new values

### PR DESCRIPTION
**Pull request by Hedrick-ARS**
Also sorted table by Value #.

### CODE REVIEW

**Comment by scotthavens** [comment]
Which ones did you add? It's a bit hard to see with the sort.

**Comment by Hedrick-ARS** [comment]
Yeah I suppose you're right. I only added 4 new classes. They were all low elevation unnatural types. It would be a pain to go compare the old and new to see what changed. I can if you want me to.

I also went through and removed a bunch of repeated classes. The problem with not having them sorted by class is that we did extra work when we all sat down and added classes in 2019.

**Comment by scotthavens** [comment]
`3108,1,0,Sonora-Mojave Semi-Desert Chaparral,2108,Sh Sonora-Mojave Semi-Desert Chaparral,Shrub,607,Shrubland,Chaparral,SRM 503: Arizona Chaparral,Shrub-dominated,Shrubland,Evergreen shrubland`

`3927,0.3,0.033,Western Warm Temperate Developed Ruderal Mixed Forest,2925,Dtm Developed Ruderal Deciduous-Evergreen Forest,Tree,15,Developed,Developed-Upland Mixed Forest,LF 20: Developed,Tree-dominated,Open tree canopy,Mixed evergreen-deciduous open tree canopy`

`3948,1,0,Western Warm Temperate Undeveloped Ruderal Shrubland,2936,Dsh Undeveloped Ruderal Shrubland,Shrub,17,Developed,Developed-Upland Shrubland,LF 20: Developed,Shrub-dominated,Shrubland,Mixed evergreen-deciduous shrubland`

`3949,1,0,Western Warm Temperate Undeveloped Ruderal Grassland,2937,Dgr Undeveloped Ruderal Grassland,Herb,16,Developed,Developed-Upland Herbaceous,LF 20: Developed,Herbaceous / Nonvascular-dominated,Herbaceous - grassland,Herbaceous - grassland`

**Review by scotthavens — APPROVED** [review]
New values look good to me, mainly grass and shruby stuff.

**Pull request merged**
